import { ClientProfile, Goal } from '../types';

export const defaultProfile: ClientProfile = {
  name: 'Patrick',
  age: 24,
  state: 'FL',
  income: 75000,
  partnerIncome: 0,
  monthlyExpenses: 3600,
  cashSavings: 9000,
  investments: 12000,
  retirement: 8000,
  currentRetirementContribution: 4650,
  debt: 15000,
  debtRate: 8.5,
  studentLoans: 6000,
  creditScore: 710,
  heightInches: 70,
  weightLbs: 180,
  relationshipStatus: 'single',
  partnerAge: 0,
  dependents: 0,
  childrenPlanned: 0,
  parentSupportMonthly: 0,
  parent1Age: 58,
  parent2Age: 57,
  expectedInheritance: 0,
  rentOrOwn: 'rent',
  rentMortgage: 1800,
  desiredHomePrice: 420000,
  downPaymentSaved: 5000,
  mortgageRate: 6.75,
  mortgageYears: 30,
  autoOwnership: 'financed',
  carMake: 'Toyota',
  carModel: 'Camry',
  carYear: 2021,
  carPayment: 425,
  carValue: 22000,
  carLoanBalance: 13500,
  carLoanRate: 7.9,
  annualTravelBudget: 12000,
  vacationsPerYear: 3,
  taxFilingStatus: 'single',
  estimatedTaxWithholding: 10500,
  annualCapitalGains: 1500,
  healthInsurance: 'employer',
  lifeInsurance: 'none',
  disabilityInsurance: 'none',
  autoInsurance: 'full',
  hasHealthInsurance: true,
  hasLifeInsurance: false,
  hasDisabilityInsurance: false,
  hasAutoInsurance: true,
  riskTolerance: 'medium',
  targetRetirementAge: 65,
};

export const defaultGoals: Goal[] = [
  { id: '1', name: 'Emergency fund', type: 'savings', targetAmount: 18000, currentAmount: 9000, years: 1, targetDate: '2027-05-27', priority: 'high' },
  { id: '2', name: 'First home down payment', type: 'purchase', targetAmount: 60000, currentAmount: 5000, years: 5, targetDate: '2031-05-27', priority: 'medium' },
  { id: '3', name: 'Retirement acceleration', type: 'savings', targetAmount: 250000, currentAmount: 8000, years: 10, targetDate: '2036-05-27', priority: 'high' },
];
